-- Rebrand outgoing email templates: add logo, styled card/button/info-box design,
-- and an internal-staff-only discard notice on the 7 staff-facing templates
-- (the other 4 go to candidates/contractors/supervisors, who are the correct
-- external recipients, so the notice does not apply to them).
-- {{logoUrl}} is substituted centrally by sendTemplatedEmail(), not per-caller.
-- Migration: 20260819000005_email_templates_rebrand.sql

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Consultation status updated</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{consultationTitle}}</strong> has a new status.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">{{oldStatus}} → <strong>{{newStatus}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{consultationUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View consultation</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$CONSULTATION STATUS UPDATED

{{consultationTitle}} has a new status.

{{oldStatus}} → {{newStatus}}

View consultation: {{consultationUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'consultation_status_changed';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">You've been assigned as consultant</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">You've been assigned to <strong>{{consultationTitle}}</strong> for <strong>{{companyName}}</strong>.</p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{consultationUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View consultation</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$YOU'VE BEEN ASSIGNED AS CONSULTANT

You've been assigned to {{consultationTitle}} for {{companyName}}.

View consultation: {{consultationUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'consultant_assigned';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Consultation due date approaching</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{consultationTitle}}</strong> is coming up on its due date.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">Due: <strong>{{dueDate}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{consultationUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View consultation</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$CONSULTATION DUE DATE APPROACHING

{{consultationTitle}} is coming up on its due date.

Due: {{dueDate}}

View consultation: {{consultationUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'due_date_reminder';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Job {{field}} updated</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{jobTitle}}</strong> has been updated.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">{{field}}: {{oldValue}} → <strong>{{newValue}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{jobUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View job</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$JOB {{FIELD}} UPDATED

{{jobTitle}} has been updated.

{{field}}: {{oldValue}} → {{newValue}}

View job: {{jobUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'job_details_changed';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Contract established</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{candidateName}}</strong> has been placed for <strong>{{jobTitle}}</strong>.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">Start date: <strong>{{startDate}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{jobUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View job</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$CONTRACT ESTABLISHED

{{candidateName}} has been placed for {{jobTitle}}.

Start date: {{startDate}}

View job: {{jobUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'contract_established';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Contract expiring soon</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{candidateName}}</strong>'s contract for <strong>{{jobTitle}}</strong> is coming to an end.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">Finish date: <strong>{{finishDate}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{jobUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View job</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$CONTRACT EXPIRING SOON

{{candidateName}}'s contract for {{jobTitle}} is coming to an end.

Finish date: {{finishDate}}

View job: {{jobUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'contract_expiring';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Opportunity stage updated</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{opportunityTitle}}</strong> has moved to a new pipeline stage.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">{{oldStage}} → <strong>{{newStage}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{opportunityUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View opportunity</a></td></tr><tr><td style="padding-top:20px"><p style="margin:0;font-size:12px;line-height:18px;color:#8a8a8a">This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let <a href="mailto:recruiters@csexecgroup.com" style="color:#8a8a8a">recruiters@csexecgroup.com</a> know.</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$OPPORTUNITY STAGE UPDATED

{{opportunityTitle}} has moved to a new pipeline stage.

{{oldStage}} → {{newStage}}

View opportunity: {{opportunityUrl}}
---
This email is intended for CS Executive Group internal staff only. If you received it by mistake, please discard it and let recruiters@csexecgroup.com know.$$ WHERE template_key = 'opportunity_stage_changed';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Timesheet submitted</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f"><strong>{{contractorName}}</strong> submitted their timesheet and it's waiting on your approval.</p></td></tr><tr><td style="padding:14px 16px;background:#faf6ec;border-left:3px solid #a4915f;border-radius:6px"><p style="margin:0 0 4px;font-size:14px;line-height:20px;color:#2b2b2b">Week of: <strong>{{weekStarting}}</strong></p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{approvalUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">Review timesheet</a></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$TIMESHEET SUBMITTED

{{contractorName}} submitted their timesheet and it's waiting on your approval.

Week of: {{weekStarting}}

Review timesheet: {{approvalUrl}}$$ WHERE template_key = 'timesheet_submitted';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Timesheet declined</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">Your timesheet for the week of <strong>{{weekStarting}}</strong> was declined:</p></td></tr><tr><td style="padding:12px 16px;background:#fef2f2;border:1px solid #fecaca;border-radius:6px;margin-bottom:16px"><p style="margin:0;font-size:14px;line-height:20px;color:#2b2b2b">{{reason}}</p></td></tr><tr><td style="padding-top:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">Amend the entries and resubmit when you're ready.</p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{timesheetUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">Amend timesheet</a></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$TIMESHEET DECLINED

Your timesheet for the week of {{weekStarting}} was declined:

{{reason}}

Amend the entries and resubmit when you're ready.

Amend timesheet: {{timesheetUrl}}$$ WHERE template_key = 'timesheet_declined';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Timesheet approved</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">Your timesheet for the week of <strong>{{weekStarting}}</strong> has been approved.</p></td></tr><tr><td align="center" style="padding-top:24px"><a href="{{timesheetUrl}}" style="display:inline-block;background:#a4915f;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 28px;border-radius:6px" target="_blank">View timesheet</a></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$TIMESHEET APPROVED

Your timesheet for the week of {{weekStarting}} has been approved.

View timesheet: {{timesheetUrl}}$$ WHERE template_key = 'timesheet_approved';

UPDATE public.email_templates SET body_html = $$<!DOCTYPE html><html dir="ltr" lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="x-apple-disable-message-reformatting"/></head><body style="margin:0;padding:24px 12px;background:#f4f3ef;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="100%" style="max-width:560px" cellpadding="0" cellspacing="0"><tr><td style="background:#ffffff;border:1px solid #e9e6dd;border-radius:12px;padding:32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding-bottom:20px;border-bottom:1px solid #e9e6dd"><img src="{{logoUrl}}" alt="CS Executive Group" height="36" style="height:36px;width:auto;display:block"/></td></tr><tr><td style="padding-top:24px"><h1 style="margin:0 0 16px;font-size:20px;line-height:28px;color:#2b2b2b;font-weight:700">Thank you for your application</h1></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">Dear {{candidateName}},</p></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">Thank you for your interest in the <strong>{{jobTitle}}</strong> role at <strong>{{companyName}}</strong> and for taking the time to apply. After careful consideration, we've decided to move forward with other candidates for this position.</p></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">We appreciate the effort you put into your application and encourage you to apply for future roles that match your skills and experience.</p></td></tr><tr><td style="padding-bottom:16px"><p style="margin:0;font-size:14px;line-height:22px;color:#3f3f3f">Kind regards</p></td></tr></table></td></tr></table></td></tr></table></body></html>$$, body_text = $$THANK YOU FOR YOUR APPLICATION

Dear {{candidateName}},

Thank you for your interest in the {{jobTitle}} role at {{companyName}} and for taking the time to apply. After careful consideration, we've decided to move forward with other candidates for this position.

We appreciate the effort you put into your application and encourage you to apply for future roles that match your skills and experience.

Kind regards$$ WHERE template_key = 'application_unsuccessful';

